name: Veracode Pipeline Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '20 5 * * 3'

jobs:
  veracode-pipeline-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Compactar arquivos
        run: |
          zip -r app.zip . -x "*.git*" ".github/*"

      - name: Executar Veracode Pipeline Scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.18
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          file: app.zip
          fail_build: false

      - name: Converter JSON para SARIF
        run: |
          curl -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip -o pipeline-scan-LATEST.zip -d scanner
          java -jar scanner/pipeline-scan.jar -f results.json --format sarif -o results.sarif

      - name: Upload do relatório no GitHub (SARIF)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
