name: Veracode Pipeline Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '20 5 * * 3'

jobs:
  veracode-pipeline-scan:
    runs-on: ubuntu-latest

    steps:
      # Baixa o código do seu repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # Compacta os arquivos em um .zip (exclui .git e workflows)
      - name: Compactar arquivos
        run: |
          zip -r app.zip . -x "*.git*" ".github/*"

      # Executa o scan com a ação oficial mais recente da Veracode
      - name: Executar Veracode Pipeline Scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.18
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          file: app.zip
          fail_build: false

      # Converte o arquivo results.json em results.sarif com Python
      - name: Converter JSON para SARIF (Python)
        run: |
          curl -O https://raw.githubusercontent.com/veracode/veracode-pipeline-scan-results-to-sarif/main/convert_json_to_sarif.py
          python3 convert_json_to_sarif.py -i results.json -o results.sarif

      # Envia o results.sarif para a aba "Code scanning alerts"
      - name: Upload do relatório no GitHub (SARIF)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
