name: Veracode Pipeline Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '20 5 * * 3'

jobs:
  veracode-pipeline-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Compactar arquivos
        run: |
          zip -r app.zip . -x "*.git*" ".github/*"

      - name: Executar Veracode Pipeline Scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.18
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          file: app.zip
          fail_build: false

      # Adicionando um passo para verificar o status e logs do Veracode
      - name: Verificar se o arquivo SARIF foi gerado
        run: |
          echo "Verificando se o arquivo SARIF foi gerado..."
          ls -lh

          # Tentando exibir o conteúdo do diretório e procurar o arquivo SARIF
          if [ ! -f results.sarif ]; then
            echo "Erro: O arquivo results.sarif não foi gerado"
            exit 1
          fi

      - name: Upload do relatório no GitHub (SARIF)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
