# Nome que aparecerá na aba "Actions" do GitHub
name: Veracode Pipeline Scan

# Quando esse workflow será executado
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '20 5 * * 3'  # Toda quarta-feira às 05:20 (horário UTC)

jobs:
  veracode-pipeline-scan:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Clona o repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # Etapa 2: Compacta os arquivos para envio ao Veracode (excluindo .git e workflows)
      - name: Compactar código-fonte em ZIP
        run: |
          zip -r app.zip . -x "*.git*" ".github/*"

      # Etapa 3: Executa o Veracode Pipeline Scan com geração do arquivo de resultado
      - name: Executar Veracode Pipeline Scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.18
        with:
          vid: ${{ secrets.VERACODE_API_ID }}     # ID da API (salvo nos Secrets do GitHub)
          vkey: ${{ secrets.VERACODE_API_KEY }}    # Chave da API
          file: app.zip                            # Arquivo compactado que será analisado
          fail_build: false                        # true = falha o job se encontrar vulnerabilidades
          output: results.json                     # Gera o relatório em formato JSON

      # Etapa 4: Baixa o script oficial da Veracode que converte JSON para SARIF
      - name: Baixar conversor JSON → SARIF
        run: |
          curl -sSLO https://raw.githubusercontent.com/veracode/veracode-pipeline-scan-results-to-sarif/main/scripts/convert_json_to_sarif.py

      # Etapa 5: Converte o arquivo JSON em SARIF (se o arquivo existir)
      - name: Converter JSON para SARIF (se existir)
        run: |
          if [ -f results.json ]; then
            python3 convert_json_to_sarif.py -i results.json -o results.sarif
          else
            echo "Arquivo results.json não encontrado. Verifique se o scan foi executado corretamente."
            exit 1
          fi

      # Etapa 6: Envia o SARIF para o GitHub para exibir na aba "Code scanning alerts"
      - name: Upload do SARIF no GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
