name: Veracode Pipeline Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '20 5 * * 3'

jobs:
  veracode-pipeline-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Compactar arquivos
        run: |
          zip -r app.zip . -x "*.git*" ".github/*"

      - name: Executar Veracode Pipeline Scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.18
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          file: app.zip
          fail_build: false

      - name: Baixar conversor JSON para SARIF
        run: |
          curl -sSLO https://raw.githubusercontent.com/veracode/veracode-pipeline-scan-results-to-sarif/main/src/convert_json_to_sarif.py

      - name: Converter JSON para SARIF (se existir)
        run: |
          if [ -f results.json ]; then
            python3 convert_json_to_sarif.py -i results.json -o results.sarif
          else
            echo "Arquivo results.json não encontrado. Verifique se o scan foi executado corretamente."
            exit 1
          fi

      - name: Upload do relatório no GitHub (SARIF)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
